const jsonHeaders = {
  "Content-Type": "application/json; charset=utf-8"
};

function corsHeaders(request, env) {
  const origin = request.headers.get("Origin") || "";
  const allowedOrigin = env.PAGES_ORIGIN || "*";

  return {
    "Access-Control-Allow-Origin": allowedOrigin === "*" ? "*" : origin === allowedOrigin ? origin : allowedOrigin,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Vary": "Origin"
  };
}

function isAllowedOrigin(request, env) {
  const allowedOrigin = env.PAGES_ORIGIN || "*";
  const origin = request.headers.get("Origin") || "";
  return allowedOrigin === "*" || origin === allowedOrigin;
}

function jsonResponse(request, env, body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      ...jsonHeaders,
      ...corsHeaders(request, env)
    }
  });
}

function cleanPhone(value) {
  return String(value || "").replace(/[^\d+() -]/g, "").trim();
}

function validate(name, phone) {
  if (name.length < 2 || name.length > 40) {
    return "Please enter a valid name.";
  }

  if (phone.replace(/\D/g, "").length < 7 || phone.length > 24) {
    return "Please enter a valid phone number.";
  }

  return "";
}

async function createIssue(env, name, phone, request) {
  const title = `Registration: ${name}`;
  const sourceCountry = request.cf?.country || "Unknown";
  const body = [
    "## Registration details",
    "",
    `- Name: ${name}`,
    `- Phone number: ${phone}`,
    `- Submitted at: ${new Date().toISOString()}`,
    `- Source country: ${sourceCountry}`,
    "",
    "---",
    "This registration was generated by the GitHub Pages + Cloudflare Worker registration form."
  ].join("\n");

  const response = await fetch(`https://api.github.com/repos/${env.PRIVATE_DATA_REPO_OWNER}/${env.PRIVATE_DATA_REPO_NAME}/issues`, {
    method: "POST",
    headers: {
      "Accept": "application/vnd.github+json",
      "Authorization": `Bearer ${env.GITHUB_TOKEN}`,
      "Content-Type": "application/json",
      "User-Agent": "github-pages-signup-form",
      "X-GitHub-Api-Version": "2022-11-28"
    },
    body: JSON.stringify({
      title,
      body,
      labels: ["registration"]
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`GitHub write failed: ${response.status} ${text}`);
  }

  return response.json();
}

export default {
  async fetch(request, env) {
    if (request.method === "OPTIONS") {
      return new Response(null, {
        status: 204,
        headers: corsHeaders(request, env)
      });
    }

    if (request.method !== "POST") {
      return jsonResponse(request, env, { ok: false, message: "Only registration submissions are supported." }, 405);
    }

    try {
      if (!isAllowedOrigin(request, env)) {
        return jsonResponse(request, env, { ok: false, message: "This origin is not allowed." }, 403);
      }

      const data = await request.json();

      if (data.website) {
        return jsonResponse(request, env, { ok: true });
      }

      const name = String(data.name || "").trim();
      const phone = cleanPhone(data.phone);
      const error = validate(name, phone);

      if (error) {
        return jsonResponse(request, env, { ok: false, message: error }, 400);
      }

      const issue = await createIssue(env, name, phone, request);
      return jsonResponse(request, env, {
        ok: true,
        issueUrl: issue.html_url
      });
    } catch (error) {
      console.error(error);
      return jsonResponse(request, env, {
        ok: false,
        message: "Submission failed. Please try again later."
      }, 500);
    }
  }
};
