name = "signup-api"
main = "cloudflare-worker.js"
compatibility_date = "2026-07-14"

[vars]
+PRIVATE_DATA_REPO_OWNER = "ObliskZhaur"
+PRIVATE_DATA_REPO_NAME = "event-signup-data"
+PAGES_ORIGIN = "https://ObliskZhaur.github.io"
